name: HTML CI CD Demo

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: TEST - Check index.html exists
      run: |
        test -f index.html

    - name: QUALITY - Check html tag
      run: |
        grep "<html>" index.html

    - name: Login to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/html-cicd-demo:latest .

    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/html-cicd-demo:latest

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker rm -f html-demo || true
          docker pull ${{ secrets.DOCKER_USERNAME }}/html-cicd-demo:latest
          docker run -d -p 80:80 --name html-demo ${{ secrets.DOCKER_USERNAME }}/html-cicd-demo:latest
