name: HTML CI CD Demo

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: TEST - Check index.html exists
      run: |
        test -f index.html

    - name: QUALITY - HTML basic quality checks
      run: |
        grep "<html>" index.html
        grep "<head>" index.html
        grep "<body>" index.html
        grep "<title>" index.html
        
    - name: Login to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/html-cicd-demo:latest .
    
        - name: SECURITY - Trivy scan Docker image
          uses: aquasecurity/trivy-action@0.24.0
          with:
            image-ref: ${{ secrets.DOCKER_USERNAME }}/html-cicd-demo:latest
            severity: HIGH,CRITICAL
            exit-code: 1
            
    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/html-cicd-demo:latest

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker rm -f html-demo || true
          docker pull ${{ secrets.DOCKER_USERNAME }}/html-cicd-demo:latest
          docker run -d -p 80:80 --name html-demo ${{ secrets.DOCKER_USERNAME }}/html-cicd-demo:latest
